### ISSUE TITLE
数据处理文件

### ISSUE THREAD

**Issue by non-knife** [ICTMCG/ENDEF-SIGIR2022#2]
师兄你好，方便提供一下BertEMO模型使用的数据处理文件吗？

**Comment by easezyc** [comment]
我提供的数据里有情感特征，如果你要处理数据的文件，你去找DualEmo的代码，我用的原始代码提取的情感特征。

**Comment by non-knife** [comment]
> 我提供的数据里有情感特征，如果你要处理数据的文件，你去找DualEmo的代码，我用的原始代码提取的情感特征。

好滴，感谢感谢
